name: Leak Check

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      sha:
        description: "The commit to check out at. Defaults to the parent workflow's github.sha."
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        ref: ${{ inputs.sha }}

    - name: Install Go
      uses: actions/setup-go@v7
      with:
        go-version: stable

    - name: Set Up Workspace
      # Submodules shouldn't cause a download.
      run: |
        set -o pipefail
        go work init . $(ls ./deps/*_*/cgo.go | xargs -r dirname)

    - name: Build Test
      env:
        CC: clang
        CXX: clang++
      run: |
        go test -c --tags leakcheck

    - name: Run Test
      run: ./v8go.test
